language: php

php:
  - 5.5
  - 5.6

env:
  matrix:
    - TYPO3_VERSION="7.6.0"
    - TYPO3_VERSION="^7.0"
    - TYPO3_VERSION="dev-master"

sudo: false

notifications:
  email:
    recipients:
      - thomas@poisl.org
    on_success: always
    on_failure: always
